preload = /home/vs/Downloads/in-the-rain.png
preload = /home/vs/Downloads/Anime-Girl-Rain.png
preload = /home/vs/Downloads/5d44a38a-7043-4621-9cc5-049fccbe5972.png
preload = /home/vs/Downloads/in-the-rain.png

wallpaper = eDP-1,/home/vs/Downloads/Anime-Girl-Rain.png
wallpaper = HDMI-A-1,/home/vs/Downloads/Anime-Girl-Rain.png

# preload = /home/vs/dev/anime/aegis-pointing-upclose.jpg
# preload = /home/vs/dev/anime/aegis-pointing.png
# preload = /home/vs/dev/anime/yellow_red_blue.png

