# https://alacritty.org/config-alacritty.html

###########
# GENERAL #
###########

# Import additional configuration files
general.import = [
 # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]

# Bug with blur my shell
# [terminal.shell]
# program = "/bin/zsh"
# args = ["-c", "gnome-extensions disable blur-my-shell@aunetx && gnome-extensions enable blur-my-shell@aunetx"]

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" }
]


[window]
blur = true
opacity = 0.85
#startup_mode = "Fullscreen"
[font]
# Normal font style
# normal = { family = "JetBrains Mono NL", style = "Medium" }
# normal = { family = "JetBrains Mono", style = "Medium" }
# normal = { family = "JetBrains Mono", style = "Light" }
normal = { family = "JetBrains Mono", style = "Regular" }
#normal = { family = "FiraMono Nerd Font Mono", style = "Medium" }

# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold

# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 16 # Default: 11.25

# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0

# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true
